### ISSUE TITLE
error with a final bundle!

### ISSUE THREAD

**Issue by ghost** [MariusVatasoiu/deno-image#4]
Thank you for the last fix, but I found another error. 
If i  start with module import https://deno.land/x/deno_image/mod.ts, everything works, but if i get bundle 'deno_image.js' i see the error. 
Screenshot: https://user-images.githubusercontent.com/75129392/101872963-7d34a700-3bc9-11eb-9d09-fb2ea1359eb6.jpg

**Comment by MariusVatasoiu** [comment]
Opened https://github.com/denoland/deno/issues/8770.
